name: CI

on:
  workflow_call:
  push:
    branches:
      - "feature/*"
      - "feat/*"
      - "fix/*"
      - "bugfix/*"
      - "hotfix/*"
      - "refact/*"
      - "refactor/*"

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Running lint
        run: |
          ls -la
          ./golangci-lint run

      - name: Test
        run: |
          ENV=test go test . -cover

      - name: Docker Examples
        working-directory: example/full
        run: |
          docker compose up -d

      - name: Test Examples
        working-directory: example/full
        run: |
          ENV=test go test ./... -cover
