name: CI

on:
  workflow_call:
  push:
    branches:
      - "feature/*"
      - "feat/*"
      - "fix/*"
      - "bugfix/*"
      - "hotfix/*"
      - "refact/*"
      - "refactor/*"

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Running scopeguard
        run: |
          go install fillmore-labs.com/scopeguard@latest
          scopeguard ./...

      - name: Running lint
        uses: golangci/golangci-lint-action@v8
        timeout-minutes: 5
        with:
          version: v2.4
          skip-cache: false

      - name: Test
        run: |
          ENV=test go test . -cover

      - name: Docker Examples
        working-directory: example/full
        run: |
          docker compose up -d

      - name: Test Examples
        working-directory: example/full
        run: |
          ENV=test go test ./... -cover
